services:
  gestao_escolar_db:
    image: mysql:8.0
    container_name: gestao_escolar_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestao_escolar
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_db_data: