spring.application.name=gestao-escolar-api

postgres_url=${POSTGRES_URL}
postgres_user=${POSTGRES_USER}
postgres_password=${POSTGRES_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.threads.virtual.enabled=true
